package cn.cycle.app.event;

public enum AppEventType {
    CHART_LOADED,
    CHART_CLOSED,
    FEATURE_SELECTED,
    FEATURE_DESELECTED,
    
    LAYER_ADDED,
    LAYER_REMOVED,
    LAYER_VISIBILITY_CHANGED,
    LAYER_ORDER_CHANGED,
    
    VIEW_CHANGED,
    ZOOM_CHANGED,
    CENTER_CHANGED,
    
    SIDEBAR_PANEL_CHANGED,
    RIGHT_TAB_CHANGED,
    STATUS_MESSAGE,
    
    SERVICE_CONNECTED,
    SERVICE_DISCONNECTED,
    SERVICE_ERROR,
    
    LOADING_STARTED,
    LOADING_PROGRESS,
    LOADING_COMPLETED,
    LOADING_STATE_CHANGED,
    
    RENDERING_STARTED,
    RENDERING_PROGRESS,
    RENDERING_COMPLETED,
    
    MEMORY_WARNING,
    MEMORY_CRITICAL,
    
    THEME_CHANGED,
    LOCALE_CHANGED,
    
    DATA_ADDED,
    DATA_REMOVED,
    DATA_PREVIEW,
    DATA_PROPERTIES
}
